<Window
        x:Class="Ngdbeambracketconnect.TabExample"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Ngdbeambracketconnect"
        xmlns:fui="http://schemas.trimble.com/fusion"
        xmlns:converter="clr-namespace:Ngdbeambracketconnect.Converter"
         xmlns:bconverter="clr-namespace:Ngdbeambracketconnect.Converter"
        xmlns:vm="clr-namespace:Ngdbeambracketconnect.ViewModel"
        xmlns:model="clr-namespace:Ngdbeambracketconnect.Model"
        xmlns:sconverter="clr-namespace:Ngdbeambracketconnect.Converter"
         xmlns:wconvert="clr-namespace:Ngdbeambracketconnect.Converter"
        xmlns:oconverter="clr-namespace:Ngdbeambracketconnect.Converter"
        xmlns:iconverter="clr-namespace:Ngdbeambracketconnect.Converter"
        xmlns:lconverter="clr-namespace:Ngdbeambracketconnect.Converter"
        xmlns:blconverter="clr-namespace:Ngdbeambracketconnect.Converter"
        xmlns:cconverter="clr-namespace:Ngdbeambracketconnect.Converter"
        xmlns:epconverter="clr-namespace:Ngdbeambracketconnect.Converter"
        xmlns:UIControls="clr-namespace:Tekla.Structures.Dialog.UIControls;assembly=Tekla.Structures.Dialog"
        mc:Ignorable="d"
        Title="TabExample" Height="740" Width="625">
    <Window.Resources>
        <converter:EnumConverter x:Key="EnumCon"></converter:EnumConverter>
        <vm:BracketViewModel x:Key="BracketViewModel"></vm:BracketViewModel>
        <bconverter:BoltStandard x:Key="BoltCon"></bconverter:BoltStandard>
        <sconverter:SpliceConverter x:Key="SpliceCon"></sconverter:SpliceConverter>
        <wconvert:WasherConverter x:Key="WashCon"></wconvert:WasherConverter>
        <oconverter:OuterConverter x:Key="OuterCon"></oconverter:OuterConverter>
        <model:BracketEnum x:Key="EnumModel"></model:BracketEnum>
        <lconverter:LengthConverter x:Key="LengthCon"></lconverter:LengthConverter>
        <blconverter:BotLength x:Key="BLengthCon"></blconverter:BotLength>
        <iconverter:InnerConverter x:Key="InnerCon"></iconverter:InnerConverter>
        <cconverter:CanopyConverter x:Key="CanopyCon"></cconverter:CanopyConverter>
        <epconverter:CanopyEp x:Key="EpCon"></epconverter:CanopyEp>
    </Window.Resources>
    <Grid DataContext="{StaticResource BracketViewModel}">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>
        <ComboBox Margin="25,10,347,10"  Height="20"></ComboBox>
        <Button Margin="305,0,217,0" Content="Save" Height="30"></Button>
        <Button Margin="505,0,10,0" Content="Help" Height="30"></Button>

        <TabControl Grid.Row="1">
            <TabItem Header="Bracket">
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="93.484" />
                        <ColumnDefinition Width="8.768"/>
                        <ColumnDefinition Width="422.232"/>
                    </Grid.ColumnDefinitions>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                    </Grid.RowDefinitions>
                    <StackPanel Grid.Column="0" Grid.Row="0" Grid.ColumnSpan="3" Orientation="Horizontal">
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="110" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto"/>
                                <ColumnDefinition Width="*"/>
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                            </Grid.RowDefinitions>
                            <Label Content="Bracket Option" VerticalAlignment="Center" Margin="2,3,0,0" />
                            <CheckBox VerticalAlignment="Center" HorizontalAlignment="Center" Margin="2,3,0,0" Grid.Column="1" IsChecked="True"></CheckBox>
                            <ComboBox Margin="2,3,0,0" Grid.Column="2" Width="145" ItemsSource="{Binding Source={StaticResource EnumCon},Path=Strings}" SelectedItem="{Binding BracketDetail,Converter={StaticResource EnumCon}}"  SelectedIndex="1"></ComboBox>

                        </Grid>
                    </StackPanel>
                    <StackPanel Grid.Column="0" Grid.Row="1" Grid.ColumnSpan="3" Orientation="Horizontal" x:Name="HotRolled" Visibility="{Binding TextBoxVisibility,Mode=TwoWay}">
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="110" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto"/>
                                <ColumnDefinition Width="*"/>
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                            </Grid.RowDefinitions>
                            <Label Content="HR Bracket" Grid.Row="0" Margin="2,3,0,0" VerticalAlignment="Center"/>
                            <CheckBox  Margin="2,3,0,0"  VerticalAlignment="Center" HorizontalAlignment="Center" Grid.Column="1" Grid.Row="1"></CheckBox>
                            <TextBox  TextWrapping="Wrap" Margin="2,3,0,0" x:Name="HotRolledProfile" Grid.Column="2" Grid.Row="1"
                                 Width="120"  Height="Auto" VerticalAlignment="Center"   Text="{Binding HotRolledProfile, Mode=TwoWay}"></TextBox>
                            <!--<UIControls:WpfProfileCatalog Grid.Column="3" Name="Details" Margin="0,4,0,3" SelectClicked="Details_SelectClicked" SelectionDone="Details_SelectionDone" />-->
                            <!--<UIControls:WpfProfileCatalog Grid.Column="3" Name="Details" Margin="0,4,0,3" SelectClicked="Details_SelectClicked" SelectionDone="Details_SelectionDone"  />-->

                        </Grid>
                    </StackPanel>
                    <StackPanel Grid.Column="0" Grid.Row="2" Grid.ColumnSpan="3" Orientation="Horizontal" x:Name="BuiltUp" Visibility="{Binding TextBoxVisibility1,Mode=TwoWay}">
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="30" />
                                <ColumnDefinition Width="Auto"/>
                                <ColumnDefinition Width="*"/>
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto"/>
                                <RowDefinition Height="*"/>
                            </Grid.RowDefinitions>

                            <Label Content="Thickness" Grid.Row="2" Grid.Column="2" HorizontalAlignment="Left" VerticalAlignment="Center"/>
                            <Label Content="Width" Grid.Row="2" Grid.Column="4" HorizontalAlignment="Left" VerticalAlignment="Center" Margin="0"/>
                            <Label Content="BU Top Flange" Grid.Row="3" VerticalAlignment="Center"/>
                            <CheckBox Grid.Column="1" Grid.Row="3"   HorizontalAlignment="Center" VerticalAlignment="Center"></CheckBox>
                            <TextBox TextWrapping="Wrap" Grid.Row="3" Grid.Column="2" Width="60" Height="Auto" fui:Extensions.Watermark="Calculated"
                                 HorizontalAlignment="Left"  VerticalAlignment="Bottom" Margin="2,0,0,2" Text="{Binding BUTopFlgThickness, Mode=TwoWay}"></TextBox>
                            <CheckBox Grid.Column="3" Grid.Row="3" VerticalAlignment="Center" HorizontalAlignment="Right"></CheckBox>
                            <TextBox  TextWrapping="Wrap" Grid.Row="3" Grid.Column="4"  Width="60" HorizontalAlignment="Left"   VerticalAlignment="Center" Text="{Binding BUTopFlangeWidth, Mode=TwoWay}" fui:Extensions.Watermark="Calculated"></TextBox>
                            <Label Content="BU Web" Grid.Row="4" VerticalAlignment="Center"/>
                            <CheckBox Grid.Column="1" HorizontalAlignment="Center" Grid.Row="4" VerticalAlignment="Center"></CheckBox>
                            <TextBox TextWrapping="Wrap"  Width="60"  Height="Auto" Grid.Column="2" Grid.Row="4"  HorizontalAlignment="Left" VerticalAlignment="Center" x:Name="BUWebThickness" Text="{Binding BUWebThickness, Mode=TwoWay}" fui:Extensions.Watermark="Calculated" ></TextBox>
                            <Label Content="BU Bottom Flange" Grid.Row="5" VerticalAlignment="Center"/>
                            <CheckBox Grid.Column="1" Grid.Row="5" HorizontalAlignment="Center" VerticalAlignment="Center"></CheckBox>
                            <TextBox TextWrapping="Wrap" Grid.Column="2" Grid.Row="5" Width="60"  Height="Auto"  HorizontalAlignment="Left"  VerticalAlignment="Center"  Text="{Binding BUBotFlangeThick, Mode=TwoWay}" fui:Extensions.Watermark="Calculated"></TextBox>
                            <CheckBox  Grid.Column="3" Grid.Row="5" VerticalAlignment="Center" HorizontalAlignment="Right"></CheckBox>
                            <TextBox TextWrapping="Wrap" Grid.Column="4" Grid.Row="5"  Width="60"  Height="Auto" HorizontalAlignment="Left"  VerticalAlignment="Center" Text="{Binding BUBotFlangeWidth, Mode=TwoWay}" ></TextBox>
                        </Grid>
                    </StackPanel>
                    <Separator Grid.Row="3" Grid.ColumnSpan="3"/>
                    <StackPanel x:Name="Stiffner" Grid.Column="0" Grid.Row="4" Grid.ColumnSpan="3">
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="30" />
                                <ColumnDefinition Width="Auto"/>
                                <ColumnDefinition Width="110"/>
                                <ColumnDefinition Width="Auto"/>
                                <ColumnDefinition Width="Auto"/>
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto"/>
                                <RowDefinition Height="*"/>
                            </Grid.RowDefinitions>
                            <Label Content="Thickness" Grid.Row="2" Grid.Column="2" HorizontalAlignment="Left" VerticalAlignment="Center"/>
                            <Label Content="Width" Grid.Row="2" Grid.Column="4" HorizontalAlignment="Left" VerticalAlignment="Center" Margin="0"/>
                            <Label Content="Top Flange Stiffner" Grid.Row="3" VerticalAlignment="Center"/>
                            <CheckBox  Grid.Column="1" Grid.Row="3" HorizontalAlignment="Center" VerticalAlignment="Center" ></CheckBox>
                            <TextBox TextWrapping="Wrap" Grid.Row="3" Grid.Column="2"  Width="60"   VerticalAlignment="Center" HorizontalAlignment="Left"  Text="{Binding TopFlangeStiffThick, Mode=TwoWay}"></TextBox>
                            <CheckBox Grid.Column="3" Grid.Row="3" VerticalAlignment="Center" HorizontalAlignment="Right" ></CheckBox>
                            <TextBox TextWrapping="Wrap" Grid.Row="3" Grid.Column="4"   Width="60" HorizontalAlignment="Left"  VerticalAlignment="Center" Text="{Binding TopFlangeStiffWidth, Mode=TwoWay}"></TextBox>
                            <Label Content="Length Option" Grid.Row="3" Grid.Column="5" VerticalAlignment="Center"/>
                            <CheckBox Grid.Column="5" Grid.Row="3" VerticalAlignment="Center" HorizontalAlignment="Right"></CheckBox>
                            <!--<ComboBox Margin="2,0,0,0" Grid.Column="6" Grid.Row="3" Width="120" Name="cblCountry" TextOptions.TextFormattingMode="Display" SelectedIndex="0">
                                <ComboBoxItem   Content="Full Length"></ComboBoxItem>
                            </ComboBox>-->
                            <!--<ComboBox Margin="2,0,0,0" Grid.Column="6" Grid.Row="3" Width="120" Name="cblCountry" ItemsSource="{Binding Source={StaticResource LengthCon},Path=Strings}" SelectedItem="{Binding TopLengthOption,Converter={StaticResource LengthCon}}" SelectedIndex="0"/>-->
                            <ComboBox Margin="2,0,0,0" Grid.Column="6" Grid.Row="3" Width="120" Name="cblCountry" ItemsSource="{StaticResource BLengthCon}"  SelectedIndex="1"/>

                            <Label Content="Length Option" Grid.Row="4" Grid.Column="5" VerticalAlignment="Center"/>
                            <CheckBox Grid.Column="5" Grid.Row="4" VerticalAlignment="Center" HorizontalAlignment="Right"></CheckBox>
                            <!--<ComboBox Margin="2,2,0,0" Grid.Column="6" Grid.Row="4" Width="120" Name="cblBracket" TextOptions.TextFormattingMode="Display" SelectedIndex="0">
                                <ComboBoxItem   Content="Full Length"></ComboBoxItem>
                            </ComboBox>-->
                            <!--<ComboBox Margin="2,2,0,0" Grid.Column="6" Grid.Row="4" Width="120" Name="cblBracket" ItemsSource="{Binding Source={StaticResource LengthCon},Path=Strings}" SelectedItem="{Binding BotLengthOption,Converter={StaticResource LengthCon}}" SelectedIndex="0"/>-->
                            <ComboBox Margin="2,2,0,0" Grid.Column="6" Grid.Row="4" Width="120" Name="cblBracket" ItemsSource="{StaticResource BLengthCon}" SelectedIndex="1"/>


                            <Label Content="Bottom Flange Stiff" Grid.Row="4" VerticalAlignment="Center"/>
                            <CheckBox Grid.Column="1" HorizontalAlignment="Center" Grid.Row="4"  VerticalAlignment="Center"></CheckBox>
                            <TextBox TextWrapping="Wrap"  Width="60"  Height="Auto" Grid.Column="2" Grid.Row="4" HorizontalAlignment="Left"  VerticalAlignment="Center" Text="{Binding BotFlangeStiffThick, Mode=TwoWay}"></TextBox>
                            <CheckBox Grid.Column="3" Grid.Row="4" VerticalAlignment="Center" HorizontalAlignment="Right"></CheckBox>
                            <TextBox TextWrapping="Wrap" Grid.Column="4" Grid.Row="4"   Width="60"  Height="Auto" HorizontalAlignment="Left"   VerticalAlignment="Center" Text="{Binding BotFlangeStiffWidth, Mode=TwoWay}"></TextBox>
                            <Label Content="Stiffner Chamfers" Grid.Row="5" VerticalAlignment="Center"/>
                            <CheckBox Grid.Column="1" Grid.Row="5" HorizontalAlignment="Center" VerticalAlignment="Center"></CheckBox>
                            <TextBox TextWrapping="Wrap" Grid.Column="2" Grid.Row="5"  Width="60"   Height="Auto" HorizontalAlignment="Left"  VerticalAlignment="Center" Text="{Binding StiffThickness, Mode=TwoWay}"></TextBox>
                        </Grid>
                    </StackPanel>
                    <Canvas Grid.Row="5" Grid.Column="0" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="70,5,0,0">
                        <Image Source="D:\Ujjwal\WPF\Ngdbeambracketconnect\Ngdbeambracketconnect\Resources\Images\NgdBeamBracketConnectGeo.png" Stretch="None"></Image>
                        <StackPanel Orientation="Horizontal"  Canvas.Left="140"  Canvas.Top="30">
                            <CheckBox VerticalAlignment="Center" IsChecked="True"/>
                            <TextBox TextWrapping="Wrap"  Width="60"  Height="23"  VerticalAlignment="Center" Text="{Binding BracketProjection, Mode=TwoWay}"></TextBox>
                        </StackPanel>
                    </Canvas>

                </Grid>
            </TabItem>
            <TabItem Header="Connection" Margin="-2,-2,-2,2">
                <Grid Margin="10">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="Auto"/>
                        <RowDefinition Height="Auto"/>
                        <RowDefinition Height="Auto"/>
                        <RowDefinition Height="Auto"/>
                    </Grid.RowDefinitions>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="Auto"/>
                        <ColumnDefinition Width="25"/>
                        <ColumnDefinition Width="582"/>
                        <ColumnDefinition Width="Auto"/>
                        <ColumnDefinition Width="20"/>
                        <ColumnDefinition Width="Auto"/>
                        <ColumnDefinition Width="*"/>
                        <ColumnDefinition Width="Auto"/>
                    </Grid.ColumnDefinitions>
                    <StackPanel Grid.ColumnSpan="3" Orientation="Horizontal">
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="120" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto"/>
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                            </Grid.RowDefinitions>
                            <TextBlock Text="Thickness" FontSize="12"  Grid.Column="2" HorizontalAlignment="Left" VerticalAlignment="Center" Margin="0,0,0,10"/>
                            <TextBlock Text="Width" FontSize="12" Grid.Column="4" HorizontalAlignment="Left" VerticalAlignment="Center" Margin="10,0,0,10"></TextBlock>
                            <TextBlock Text="Bracket Conn. Plate" Grid.Row="1" HorizontalAlignment="Left" VerticalAlignment="Center" Margin="0,0,10,0"></TextBlock>
                            <CheckBox Grid.Column="1" Grid.Row="1" HorizontalAlignment="Left" VerticalAlignment="Center"  Margin="0,0,0,5"></CheckBox>
                            <TextBox TextWrapping="Wrap" Grid.Column="2" Grid.Row="1" Width="60" Height="Auto"  HorizontalAlignment="Left" VerticalAlignment="Center" Margin="0,0,0,5"  x:Name="BracketEPThickness"
                                  Text="{Binding BracketEPThickness, Mode=TwoWay}"></TextBox>
                            <CheckBox Grid.Column="3" Grid.Row="1" HorizontalAlignment="Right" VerticalAlignment="Center"  Margin="0,0,0,5"></CheckBox>
                            <TextBox TextWrapping="Wrap" Grid.Column="4" Grid.Row="1"  Width="60"  Height="Auto" HorizontalAlignment="Left"  VerticalAlignment="Center" Margin="5,0,0,5" x:Name="BracketEPWidth"
                                  Text="{Binding BracketEPWidth, Mode=TwoWay}" ></TextBox>
                            <TextBlock Text="Beam Conn. Plate" Grid.Row="2" HorizontalAlignment="Left" VerticalAlignment="Center" Margin="0,0,10,0" RenderTransformOrigin="0.484,1.125"></TextBlock>
                            <CheckBox Grid.Column="1" Grid.Row="2" HorizontalAlignment="Left" VerticalAlignment="Center"></CheckBox>
                            <TextBox TextWrapping="Wrap" Grid.Column="2" Grid.Row="2"  Width="60"  Height="Auto"  HorizontalAlignment="Left"  VerticalAlignment="Center" Margin="0,0,0,0"  x:Name="BeamEPThickness"
                                  Text="{Binding BeamEPThickness, Mode=TwoWay}" ></TextBox>
                            <CheckBox Grid.Column="3" Grid.Row="2" HorizontalAlignment="Right" VerticalAlignment="Center"></CheckBox>
                            <TextBox TextWrapping="Wrap" Grid.Column="4" Grid.Row="2"  Width="60"  Height="Auto"  HorizontalAlignment="Left" VerticalAlignment="Center" Margin="5,0,0,0"  x:Name="BeamEPWidth"
                                  Text="{Binding BeamEPWidth, Mode=TwoWay}"></TextBox>

                        </Grid>
                    </StackPanel>
                    <Separator Grid.Row="1" Grid.ColumnSpan="5"/>
                    <StackPanel Grid.Row="2" Grid.ColumnSpan="3" Orientation="Horizontal" Margin="0,10,0,0">
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="110" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto"/>
                                <ColumnDefinition Width="Auto"/>
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                            </Grid.RowDefinitions>
                            <TextBlock Text="Bolt Standard" HorizontalAlignment="Left" VerticalAlignment="Center"></TextBlock>
                            <CheckBox Grid.Column="1" HorizontalAlignment="Right" VerticalAlignment="Center"></CheckBox>
                            <ComboBox Width="150" Grid.Column="2" VerticalAlignment="Center" HorizontalAlignment="Left" Height="Auto" Margin="5,0,0,5" ItemsSource="{StaticResource BoltCon}" SelectedIndex="0"></ComboBox>
                            <TextBlock Text="Bolt Diameter" Grid.Row="1" HorizontalAlignment="Left" VerticalAlignment="Center" Margin="0,0,10,0"></TextBlock>
                            <CheckBox  Grid.Column="1" Grid.Row="1" HorizontalAlignment="Right" VerticalAlignment="Center"></CheckBox>
                            <TextBox Width="150" Grid.Column="2" Grid.Row="1"  VerticalAlignment="Center" HorizontalAlignment="Left" Margin="5,0,0,5" Text="{Binding BoltDiameter, Mode=TwoWay}"></TextBox>
                            <TextBlock Text="Bolt Tolerance" Grid.Row="2" HorizontalAlignment="Left" VerticalAlignment="Center"></TextBlock>
                            <CheckBox Grid.Column="1" Grid.Row="2" HorizontalAlignment="Right" VerticalAlignment="Center"></CheckBox>
                            <TextBox Width="150" Grid.Column="2" Grid.Row="2"  VerticalAlignment="Center" HorizontalAlignment="Left" Margin="5,0,0,5" Text="{Binding BoltTolerance, Mode=TwoWay}"></TextBox>
                            <TextBlock Text="Splice Bolts" Grid.Row="3" HorizontalAlignment="Left" VerticalAlignment="Center" Margin="0,0,10,0"></TextBlock>
                            <CheckBox Grid.Column="1" Grid.Row="3" HorizontalAlignment="Right" VerticalAlignment="Center"></CheckBox>
                            <ComboBox Grid.Column="2" Grid.Row="3" VerticalAlignment="Center"  HorizontalContentAlignment="Left" Margin="5,0,0,5" ItemsSource="{Binding Source={StaticResource SpliceCon},Path=Strings}" SelectedItem="{Binding SpliceBoltOption,Converter={StaticResource SpliceCon}}" SelectedIndex="1"></ComboBox>

                            <StackPanel Grid.Column="5" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="15,0,0,0">
                                <Grid>
                                    <Grid.ColumnDefinitions>
                                        <ColumnDefinition Width="120" />
                                        <ColumnDefinition Width="20" />
                                        <ColumnDefinition Width="Auto" />
                                        <ColumnDefinition Width="20" />
                                        <ColumnDefinition Width="Auto"/>
                                    </Grid.ColumnDefinitions>
                                    <Grid.RowDefinitions>
                                        <RowDefinition Height="Auto" />
                                    </Grid.RowDefinitions>
                                    <TextBlock Text="Hardened Flat Washer"  HorizontalAlignment="Left" VerticalAlignment="Center" Margin="-5,0,0,0"></TextBlock>
                                    <CheckBox Grid.Column="1" HorizontalAlignment="Left" VerticalAlignment="Center"></CheckBox>
                                    <ComboBox  Grid.Column="2" VerticalAlignment="Center"  HorizontalContentAlignment="Left" HorizontalAlignment="Left" Width="120" ItemsSource="{Binding Source={StaticResource WashCon},Path=Strings}" SelectedItem="{Binding WasherOption,Converter={StaticResource WashCon}}" SelectedIndex="1" />

                                </Grid>
                            </StackPanel>
                        </Grid>
                    </StackPanel>
                    <Canvas Grid.Column="0" Grid.ColumnSpan="3"  Height="458" Width="580" HorizontalAlignment="Left" Grid.Row="3" VerticalAlignment="Top" Margin="0,0,0,0">
                        <Grid Height="455">
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="auto" />
                                <ColumnDefinition Width="auto" />
                                <ColumnDefinition Width="*" />
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                            </Grid.RowDefinitions>
                            <CheckBox HorizontalAlignment="Right" VerticalAlignment="Center" Margin="0,0,0,5"></CheckBox>
                            <ComboBox Grid.Column="1" VerticalAlignment="Center"  HorizontalContentAlignment="Left" ItemsSource="{Binding Source={StaticResource OuterCon},Path=Strings}" SelectedItem="{Binding OuterBoltOption,Converter={StaticResource OuterCon}}" SelectedIndex="1" Margin="5,0,0,0"></ComboBox>
                            <Image Grid.ColumnSpan="3" Grid.Row="1" Visibility="{Binding Image1, Mode=OneWay}" Source="D:\Ujjwal\WPF\Ngdbeambracketconnect\Ngdbeambracketconnect\Resources\Images\NgdBeamBracketConnectBP-1.png" Stretch="None"  ></Image>
                            <Image Grid.ColumnSpan="3" Grid.Row="1" Visibility="{Binding Image2, Mode=OneWay}" Source="D:\Ujjwal\WPF\Ngdbeambracketconnect\Ngdbeambracketconnect\Resources\Images\NgdBeamBracketConnectIF-1.png" Stretch="None" ></Image>
                            <Image Grid.ColumnSpan="3" Grid.Row="1" Visibility="{Binding Image3, Mode=OneWay}" Source="D:\Ujjwal\WPF\Ngdbeambracketconnect\Ngdbeambracketconnect\Resources\Images\NgdBeamBracketConnectIF_EX-1.png" Stretch="None"  ></Image>
                            <Image Grid.ColumnSpan="3" Grid.Row="1" Visibility="{Binding Image4, Mode=OneWay}" Source="D:\Ujjwal\WPF\Ngdbeambracketconnect\Ngdbeambracketconnect\Resources\Images\NgdBeamBracketConnectEX-1.png" Stretch="None" ></Image>
                            <CheckBox  Grid.Row="2" HorizontalAlignment="Right" VerticalAlignment="Center" Margin="0,-30,0,0"></CheckBox>
                            <ComboBox Grid.Row="2" Grid.Column="1" VerticalAlignment="Center"  HorizontalContentAlignment="Left" ItemsSource="{Binding Source={StaticResource InnerCon},Path=Strings}" SelectedItem="{Binding InnerBoltOption,Converter={StaticResource InnerCon} }" Margin="5,-30,0,0" ></ComboBox>
                        </Grid>
                        <StackPanel Orientation="Horizontal" Canvas.Left="168" Canvas.Top="67">
                            <CheckBox VerticalAlignment="Center" Margin="0,-60,0,0"></CheckBox>
                            <TextBox TextWrapping="Wrap" Width="60"   Height="23" VerticalAlignment="Center" Margin="0,-60,0,0" x:Name="BoltGage" Text="{Binding BoltGage, Mode=TwoWay}"></TextBox>
                        </StackPanel>
                        <StackPanel Orientation="Horizontal" Canvas.Left="198"  Canvas.Top="108">
                            <CheckBox VerticalAlignment="Center" Margin="0,-60,0,0"></CheckBox>
                            <TextBox TextWrapping="Wrap"  Width="60" Height="23" VerticalAlignment="Center" Margin="0,-60,0,0"  x:Name="OuterBoltOffset" Text="{Binding OuterBoltOffset, Mode=TwoWay}"></TextBox>
                        </StackPanel>
                        <StackPanel Orientation="Horizontal"  Canvas.Left="198"  Canvas.Top="146">
                            <CheckBox VerticalAlignment="Center" Margin="0,-60,0,0"></CheckBox>
                            <TextBox TextWrapping="Wrap" Width="60"  Height="23"  VerticalAlignment="Center" Margin="0,-60,0,0" x:Name="OuterBoltQuantity" Text="{Binding OuterBoltQuantity, Mode=TwoWay}"></TextBox>
                        </StackPanel>
                        <StackPanel  Orientation="Horizontal"  Canvas.Left="198"  Canvas.Top="169">
                            <CheckBox  VerticalAlignment="Center" Margin="0,-60,0,0"></CheckBox>
                            <TextBox TextWrapping="Wrap"  Width="60"  Height="23"   VerticalAlignment="Center" Margin="0,-60,0,0"></TextBox>
                        </StackPanel>
                        <StackPanel Orientation="Horizontal" Canvas.Left="433" Canvas.Top="67" >
                            <CheckBox VerticalAlignment="Center" Margin="0,-60,0,0"></CheckBox>
                            <TextBox TextWrapping="Wrap" Width="60" Height="23" VerticalAlignment="Center" Margin="0,-60,0,0" x:Name="OutsideOverhang" Text="{Binding OutsideOverhang, Mode=TwoWay}"></TextBox>
                        </StackPanel>
                        <StackPanel Orientation="Horizontal" Canvas.Left="198" Canvas.Top="322"  >
                            <CheckBox VerticalAlignment="Center" Margin="0,-60,0,0"></CheckBox>
                            <TextBox TextWrapping="Wrap"  Width="60" Height="23" VerticalAlignment="Center" Margin="0,-60,0,0"></TextBox>
                        </StackPanel>
                        <StackPanel Orientation="Horizontal"  Canvas.Left="198" Canvas.Top="350">
                            <CheckBox VerticalAlignment="Center" Margin="0,-60,0,0"></CheckBox>
                            <TextBox TextWrapping="Wrap"  Width="60" Height="23" VerticalAlignment="Center" Margin="0,-60,0,0" x:Name="InnerBoltQuantity" Text="{Binding InnerBoltQuantity, Mode=TwoWay}"></TextBox>
                        </StackPanel>
                        <StackPanel Orientation="Horizontal"  Canvas.Left="198"  Canvas.Top="404">
                            <CheckBox VerticalAlignment="Center" Margin="0,-60,0,0"></CheckBox>
                            <TextBox TextWrapping="Wrap"  Width="60" Height="23"  VerticalAlignment="Center" Margin="0,-60,0,0"  x:Name="InnerBoltOffset" Text="{Binding InnerBoltOffset, Mode=TwoWay}"></TextBox>
                        </StackPanel>
                        <StackPanel Orientation="Horizontal" Canvas.Left="421"   Canvas.Top="432">
                            <CheckBox VerticalAlignment="Center" Margin="0,-70,0,0"></CheckBox>
                            <TextBox TextWrapping="Wrap"  Width="60" Height="23"  VerticalAlignment="Center" Margin="0,-70,0,0" x:Name="InsideOverhang" Text="{Binding InsideOverhang, Mode=TwoWay}"></TextBox>
                        </StackPanel>
                    </Canvas>
                </Grid>
            </TabItem>
            <TabItem Header="Canopy" Margin="-2,-2,-2,2">
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="93.484"></ColumnDefinition>
                        <ColumnDefinition Width="8.768"></ColumnDefinition>
                        <ColumnDefinition Width="422.232"></ColumnDefinition>
                    </Grid.ColumnDefinitions>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />

                    </Grid.RowDefinitions>
                    <StackPanel Grid.Column="0" Grid.Row="0" Grid.ColumnSpan="3" Orientation="Horizontal">
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="110" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto"/>
                                <ColumnDefinition Width="*"/>
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                            </Grid.RowDefinitions>
                            <Label Content="Canopy Option" VerticalAlignment="Center" Margin="2,3,0,0"></Label>
                            <CheckBox VerticalAlignment="Center" HorizontalAlignment="Center" Margin="2,3,0,0" Grid.Column="1" IsChecked="True"></CheckBox>
                            <ComboBox Margin="2,3,0,0" Grid.Column="2" Width="145" SelectedIndex="1" ItemsSource="{Binding Source={StaticResource CanopyCon},Path=Strings}" SelectedItem="{Binding CanopyDetail,Converter={StaticResource CanopyCon}}"></ComboBox>
                        </Grid>
                    </StackPanel>
                    <StackPanel Grid.Column="0" Grid.Row="1" Grid.ColumnSpan="3" Orientation="Horizontal" x:Name="HotRolled1"  Visibility="{Binding ImageVisible1,Mode=TwoWay}"  >
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="110" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto"/>
                                <ColumnDefinition Width="*"/>
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                            </Grid.RowDefinitions>
                            <Label Content="HR Canopy" Grid.Row="0" Margin="2,-5,0,-17" VerticalAlignment="Center" Height="26"></Label>
                            <CheckBox Margin="5,-5,2,-23" VerticalAlignment="Center" HorizontalAlignment="Center" Grid.Column="1" Height="25" Width="13"/>
                            <TextBox TextWrapping="Wrap" Margin="2,-5,165,-17" Grid.Column="2"  Height="Auto" VerticalAlignment="Center" Width="120" />

                        </Grid>
                    </StackPanel>
                    <StackPanel Grid.Column="2" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="15,0,0,0" >
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="120" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto"/>
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                            </Grid.RowDefinitions>
                            <TextBlock Text="Thickness" HorizontalAlignment="Left" VerticalAlignment="Center" Margin="150,53,-90,0" Width="50" Height="16" Grid.Column="4"/>
                            <TextBlock Text="Width" HorizontalAlignment="Left" VerticalAlignment="Center" Margin="260,43,-275,-9" Grid.Column="4" Height="15" Width="55" />
                            <TextBlock Text="Canopy Endplate"  HorizontalAlignment="Left" VerticalAlignment="Center" Grid.Column="4" Height="20" Margin="30,50,-15,-39" Width="105"></TextBlock>
                            <CheckBox HorizontalAlignment="Left" VerticalAlignment="Center" Grid.Column="4" Height="20" Margin="135,57,-35,-39" Width="15" ></CheckBox>
                            <TextBox HorizontalAlignment="Left" VerticalAlignment="Center" Grid.Column="4" Width="50" Margin="155,50,-90,-39" Height="20"></TextBox>
                            <CheckBox HorizontalAlignment="Left" VerticalAlignment="Center" Grid.Column="4" Height="20" Margin="240,57,-125,-34" Width="15"></CheckBox>
                            <TextBox HorizontalAlignment="Left" VerticalAlignment="Center" Grid.Column="4" Width="50" Height="20" Margin="260,50,-210,-39"></TextBox>
                            <TextBlock Text="Canopy EP Option" HorizontalAlignment="Left" VerticalAlignment="Center" Grid.Column="4" Height="27" Width="105" Margin="30,96,-5,-54"></TextBlock>
                            <CheckBox  HorizontalAlignment="Left" VerticalAlignment="Center" Grid.Column="4" Height="20" Width="15" Margin="135,102,-20,-53"></CheckBox>
                            <ComboBox  HorizontalAlignment="Right" VerticalAlignment="Center" Grid.Column="4" Height="20" Margin="0,100,-180,-51" Width="155" ItemsSource="{StaticResource EpCon}" SelectedIndex="0" >
                                <!--<ComboBoxItem   Content="Standard"></ComboBoxItem>-->
                            </ComboBox>
                        </Grid>
                    </StackPanel>
                    <StackPanel Grid.Column="0" Grid.Row="2" Grid.ColumnSpan="3" Orientation="Horizontal"  Visibility="{Binding ImageVisible,Mode=TwoWay}" Margin="0,-10,0,0" >
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="20" />
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="30" />
                                <ColumnDefinition Width="Auto"/>
                                <ColumnDefinition Width="*"/>
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto"/>
                                <RowDefinition Height="*"/>
                            </Grid.RowDefinitions>
                            <Label Content="Thickness" Grid.Row="2" Grid.Column="2" HorizontalAlignment="Left" VerticalAlignment="Center" Margin="0,15,0,0"/>
                            <Label Content="Width" Grid.Row="2" Grid.Column="4" HorizontalAlignment="Left" VerticalAlignment="Center" Margin="0,15,0,0"/>
                            <Label Content="BU Top Flange" Grid.Row="3" VerticalAlignment="Center"/>
                            <CheckBox Grid.Column="1" Grid.Row="3"   HorizontalAlignment="Center" VerticalAlignment="Center"></CheckBox>
                            <TextBox TextWrapping="Wrap" Grid.Row="3" Grid.Column="2" Width="60" Height="Auto" 
                                 HorizontalAlignment="Left"  VerticalAlignment="Bottom" Margin="2,0,0,2"></TextBox>
                            <CheckBox Grid.Column="3" Grid.Row="3" VerticalAlignment="Center" HorizontalAlignment="Right"></CheckBox>
                            <TextBox  TextWrapping="Wrap" Grid.Row="3" Grid.Column="4"  Width="60" HorizontalAlignment="Left"   VerticalAlignment="Center" ></TextBox>
                            <Label Content="BU Web" Grid.Row="4" VerticalAlignment="Center"/>
                            <CheckBox Grid.Column="1" HorizontalAlignment="Center" Grid.Row="4" VerticalAlignment="Center"></CheckBox>
                            <TextBox TextWrapping="Wrap"  Width="60"  Height="Auto" Grid.Column="2" Grid.Row="4"  HorizontalAlignment="Left" VerticalAlignment="Center" ></TextBox>
                            <Label Content="BU Bottom Flange" Grid.Row="5" VerticalAlignment="Center"/>
                            <CheckBox Grid.Column="1" Grid.Row="5" HorizontalAlignment="Center" VerticalAlignment="Center"></CheckBox>
                            <TextBox TextWrapping="Wrap" Grid.Column="2" Grid.Row="5" Width="60"  Height="Auto"  HorizontalAlignment="Left"  VerticalAlignment="Center" ></TextBox>
                            <CheckBox  Grid.Column="3" Grid.Row="5" VerticalAlignment="Center" HorizontalAlignment="Right"></CheckBox>
                            <TextBox TextWrapping="Wrap" Grid.Column="4" Grid.Row="5"  Width="60"  Height="Auto" HorizontalAlignment="Left"  VerticalAlignment="Center" ></TextBox>


                        </Grid>
                    </StackPanel>
                    <Canvas  Grid.Column="0" Grid.ColumnSpan="6"  Height="480" Width="580" HorizontalAlignment="Left" Grid.Row="4" VerticalAlignment="Top" Margin="20,10,0,0">
                        <Grid Height="455">
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="auto" />
                                <ColumnDefinition Width="auto" />
                                <ColumnDefinition Width="*" />
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                            </Grid.RowDefinitions>
                            <Image Grid.ColumnSpan="3" Grid.Row="1" Source="D:\Ujjwal\WPF\Ngdbeambracketconnect\Ngdbeambracketconnect\Resources\Images\NgdCanopyBeamHR.png" Stretch="None" Margin="0,-58,0,0" ></Image>
                            <Image Grid.ColumnSpan="3" Grid.Row="1" Visibility="{Binding ImageVisible, Mode=OneWay}" Source="D:\Ujjwal\WPF\Ngdbeambracketconnect\Ngdbeambracketconnect\Resources\Images\NgdCanopyBeamBU.png" Stretch="None" Margin="0,-58,0,0" Grid.RowSpan="2" />
                            <CheckBox VerticalAlignment="Center" Margin="394,24,161,374" Height="14" Grid.Column="2" Grid.Row="1"/>
                            <TextBox VerticalAlignment="Center" Grid.Column="2" Grid.Row="1" Width="60" Margin="416,25,101,368"/>
                            <TextBox VerticalAlignment="Center" Grid.Column="2" Grid.Row="1" Width="60" Margin="356,106,161,288"></TextBox>
                            <CheckBox VerticalAlignment="Center" Height="22" Grid.Column="2" Grid.Row="1" Margin="338,107,226,288" />
                            <CheckBox VerticalAlignment="Center" Height="22" Grid.Column="2" Grid.Row="1" Margin="150,185,412,217" Visibility="{Binding ImageVisible, Mode=OneWay}" />
                            <TextBox VerticalAlignment="Center" Grid.Column="2" Grid.Row="1" Width="60" Margin="170,186,347,218" Visibility="{Binding ImageVisible, Mode=OneWay}"/>
                            <CheckBox VerticalAlignment="Center" Height="22" Grid.Column="2" Grid.Row="1" Margin="435,187,127,218" Visibility="{Binding ImageVisible, Mode=OneWay}" />
                            <TextBox VerticalAlignment="Center" Grid.Column="2" Grid.Row="1" Width="60" Margin="455,183,62,216" Visibility="{Binding ImageVisible, Mode=OneWay}"/>
                            <TextBox VerticalAlignment="Center" Grid.Column="2" Grid.Row="1" Width="60" Margin="291,291,226,116"/>
                            <CheckBox VerticalAlignment="Center" Height="22" Grid.Column="2" Grid.Row="1" Margin="271,292,291,117" />

                        </Grid>
                    </Canvas>

                </Grid>

            </TabItem>
        </TabControl>
        <Image Source="D:\Ujjwal\WPF\HelloWorld\CRUD\Resources\images\CompanyLogoFull.png"   Grid.Row="1"   Stretch="None"  HorizontalAlignment="Right"  VerticalAlignment="Top"  Margin="0,35,-610,0" Height="180">
            <Image.RenderTransform>
                <TransformGroup>
                    <ScaleTransform ScaleX="0.2" ScaleY="0.2"/>
                    <SkewTransform/>
                    <RotateTransform/>
                    <TranslateTransform/>
                </TransformGroup>
            </Image.RenderTransform>
        </Image>
        <Button Grid.Row="2" Content="OK" Margin="10,10,522,10" Width="80"></Button>
        <Button Grid.Row="2" Content="Apply" Margin="110,10,412,10" Width="80"></Button>
        <Button Grid.Row="2" Content="Modify" Margin="210,10,287,10" Width="80"></Button>
        <Button Grid.Row="2" Content="Get" Margin="310,10,182,10" Width="80"></Button>
        <CheckBox Grid.Row="2"  Margin="430,15,167,10" ></CheckBox>
        <Label Grid.Row="2" Content="/" Margin="450,10,152,0"  ></Label>
        <CheckBox Grid.Row="2" Margin="470,15,132,10"></CheckBox>
        <Button Grid.Row="2" Content="Cancel" Margin="500,10,0,10" Width="80"></Button>
    </Grid>
</Window>
